### ISSUE TITLE
MicroSD Slot on motherboard dead

### ISSUE THREAD

**Issue by BenMitnicK** [mattytrog/Simple-UF2#1]
The slot of my Micro SD Card on the motherboard is dead Is it possible to launch a Payload directly on the nand or the chip directly to be able to use the Switch on his dock in USB ??

**Comment by mattytrog** [comment]
Payloads are limited in size.

You can launch a default configuration but you will have no sleep mode libraries (on SD card) and no homebrew (on SD card). SD card readers are cheap enough to buy. Cheers :)

**Comment by BenMitnicK** [comment]
no it's not that I have a 128go sd card that no longer serves me, my motherboard slot is dead I can no longer use SD card. now I have a switch with a switchme without SD card slot, you understand? is it possible to boot on the switchme or the nand or a usb key on the dock? apart from a sd card

**Comment by mattytrog** [comment]
You can run your console as stock but that is all. Sorry

**Comment by BenMitnicK** [comment]
Ok 😔 thx
